// <copyright file="ProcessorEntryPoints.cs" company="Hypertherm Inc.">
// Copyright (c) Hypertherm Inc. All rights reserved.
// </copyright>

//------------------------------------------------------------------------------------------
//  This file was initially generated by the Robotmaster Processor Definition Editor (PDE).
//
//  Please do not change the name or signature of this class and its predefined methods.
//  Doing so will likely cause problems and incorrect behavior.
//------------------------------------------------------------------------------------------
namespace Robotmaster.Processor.Fanuc
{
    using Robotmaster.Processor.Fanuc.AdditiveProcess;
    using Robotmaster.Processor.Fanuc.CuttingProcess;
    using Robotmaster.Processor.Fanuc.Generated.Artifacts.Processes;
    using Robotmaster.Processor.Fanuc.Generated.Interfaces;
    using Robotmaster.Processor.Fanuc.PlasmaCuttingProcess;
    using Robotmaster.Processor.Fanuc.WeldingProcess;

    /// <summary>
    ///     This class has the entry points for processing each of the available processor stages.
    /// </summary>
    internal static class ProcessorEntryPoints
    {
        /// <summary>
        ///     This method is executed when main processing every operation.
        /// </summary>
        /// <param name="operation">
        ///     The current operation being processed.
        /// </param>
        /// <param name="context">
        ///     The available context.
        /// </param>
        internal static void RunMainProcessor(IOperation operation, IMainProcessorContext context)
        {
            // Add your main processor logic here.
            switch (context.Setup.SelectedProcess)
            {
                case AvailableProcess.Cutting:
                    var cuttingMainProcessor = new CuttingMainProcessor(operation, context);
                    cuttingMainProcessor.Run();
                    break;

                case AvailableProcess.Additive:
                    var additiveMainProcessor = new AdditiveMainProcessor(operation, context);
                    additiveMainProcessor.Run();
                    break;

                case AvailableProcess.PlasmaCutting:
                    var plasmaCuttingMainProcessor = new PlasmaCuttingMainProcessor(operation, context);
                    plasmaCuttingMainProcessor.Run();
                    break;

                case AvailableProcess.Welding:
                    var weldingMainProcessor = new WeldingMainProcessor(operation, context);
                    weldingMainProcessor.Run();
                    break;

                case AvailableProcess.None:
                default:
                    var mainProcessor = new MainProcessor(operation, context);
                    mainProcessor.Run();
                    break;
            }
        }

        /// <summary>
        ///     This method is executed when post-processing every program.
        /// </summary>
        /// <param name="program">
        ///     The current program being processed.
        /// </param>
        /// <param name="context">
        ///     The available context.
        /// </param>
        internal static void RunPostProcessor(IProgram program, IPostProcessorContext context)
        {
            // Add your post processor logic here.
            switch (context.Setup.SelectedProcess)
            {
                case AvailableProcess.Cutting:
                    var cuttingPostProcessor = new CuttingPostProcessor(program, context);
                    cuttingPostProcessor.Run();
                    break;

                case AvailableProcess.Additive:
                    var additivePostProcessor = new AdditivePostProcessor(program, context);
                    additivePostProcessor.Run();
                    break;

                case AvailableProcess.PlasmaCutting:
                    var plasmaCuttingPostProcessor = new PlasmaCuttingPostProcessor(program, context);
                    plasmaCuttingPostProcessor.Run();
                    break;

                case AvailableProcess.Welding:
                    var weldingPostProcessor = new WeldingPostProcessor(program, context);
                    weldingPostProcessor.Run();
                    break;

                case AvailableProcess.None:
                default:
                    var postProcessor = new PostProcessor(program, context);
                    postProcessor.Run();
                    break;
            }
        }
    }
}
